files:
  disk: ""
  source: ""
separator: "."
indent-spaces: 2
version:
  pattern:
    - 01-99
    - "."
    - ["a", "b"]
  file-path: ""
relocations:
  1.2.3:
    a.b: c.d
section-values:
  1.2.3:
    - "a"
    - "b"